project:
  type: website
  output-dir: docs

website:
  title: "Prana_updates"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - documentation.qmd
      - anothersection.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



